name: BDXITV Auto IPTV Build


on:

  workflow_dispatch:


  schedule:

    - cron: "*/30 * * * *"


permissions:

  contents: write



jobs:


  build:


    runs-on: ubuntu-latest


    steps:


      - name: Checkout Repository
        uses: actions/checkout@v4



      - name: Setup Python

        uses: actions/setup-python@v5

        with:

          python-version: "3.11"



      - name: Install Python Packages

        run: |

          pip install pyzipper requests



      - name: Extract Password ZIP

        env:

          ZIP_PASSWORD: ${{ secrets.ZIP_PASSWORD }}


        run: |

          python <<'PY'

          import pyzipper
          import os


          zip_file = "bdxitv.zip"

          password = os.environ["ZIP_PASSWORD"].encode()



          with pyzipper.AESZipFile(
              zip_file,
              "r"
          ) as z:

              z.setpassword(password)

              z.extractall(".")



          print("ZIP Extract Completed")

          PY




      - name: Run IPTV Builder

        run: |

          python build.py





      - name: Commit vip.m3u8


        run: |


          git config user.name "github-actions[bot]"

          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"



          git add vip.m3u8



          git commit -m "Auto update vip.m3u8" || echo "No changes"



          git push
