name: Fifa_world_cup_pro Bot

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */6 * * *"


jobs:
  update:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      - name: Install packages
        run: |
          pip install -r requirements.txt


      - name: Run Python
        env:
          PLAYLIST_URL: ${{ secrets.PLAYLIST_URL }}
        run: |
          python Fifa.py


      - name: Save result
        run: |
          git config --global user.name "Fifa_world_cup_pro Bot"
          git config --global user.email "github-actions@github.com"

          git add .

          git commit -m "Auto update Fifa_world_cup_pro" || echo "No changes"

          git push
