name: IPTV Auto Builder

on:
  workflow_dispatch:
  schedule:
    - cron: "*/45 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run IPTV script
        env:
          INPUT_URL: ${{ secrets.INPUT_URL }}
        run: python src/main.py

      - name: Commit output files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add output/bd_fifa.m3u8 output/channels.json

          git commit -m "auto update playlist" || echo "No changes"

          git push
